### ISSUE TITLE
Transcription du fichier 064 du Cid

### ISSUE THREAD

**Issue by Lwizzzzzz** [Jean-Baptiste-Camps/OCR_workshop#1]
Cette issue porte sur la transcription du fichier 064 du Cid_princeps suite à l'atelier OCR du mercredi 9 janvier à l'ENC. Cette transcription a été réalisée par Louise Dutertre (M2 TNAH).

**Comment by Jean-Baptiste-Camps** [comment]
Réglé par #2 .
