### ISSUE TITLE
Transcription de la p. 317 de la Mer des histoires

### ISSUE THREAD

**Issue by olivierjacquot** [Jean-Baptiste-Camps/OCR_workshop#3]
La lettre "v" n'a pas faut l'objet d'un codage particulier malgré sa graphie spécifique. Transcribe propose une ligne de transcription -qui n'a pas été remplie- pour des chiffres en exposant. Les césures de mot sont parfois marquées de la barre oblique habituelle et ont été codées mais ce n'est pas systématique de la part du scripteur.

**Comment by Jean-Baptiste-Camps** [comment]
Pour *v*, voulez-vous dire que vous avez conservé la distinction graphique entre les deux formes *v* et *u* telles que dans la source, sans normalisation phonologique (consonne / voyelle), ou que tout a été aligné sur *u* ?

**Comment by Jean-Baptiste-Camps** [comment]
Solved by #5
